version: '2'
services:
  web:
       build:
               context: ./rah-rest-webservices
               dockerfile: Dockerfile
       container_name: hello_app
       volumes:
          - ./rah-rest-webservices:/var/www/html/
       ports:
         - 8008:80
 
